name: Kustomize
description: |
  Edits the kustomize files to update the image tags.
inputs:
  build_strategy:
    required: true
    description: The build strategy to use (docker|aws).
    default: docker
  docker_registry:
    required: false
    description: |
      The docker registry to build+push the image to.
      For AWS this is usually <account-id>.dkr.ecr.<region>.amazonaws.com
  docker_username:
    required: false
    description: |
      The username to use for the docker registry.
      For AWS, this is the AWS access key ID.
  docker_password:
    required: false
    description: |
      The password to use for the docker registry.
      For AWS, this is the AWS secret access key.
  docker_image_name:
    required: true
    description: The AWS docker image name to build+push the image to.
  docker_tag_push:
    required: true
    description: The tag to push the image to.
runs:
  using: composite
  steps:
    - name: Go Mod Vendor
      shell: bash
      run: go mod vendor
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
    - name: Docker Build and Push
      uses: docker/build-push-action@v4
      with:
        context: "."
        push: true
        tags: ${{ inputs.docker_registry }}/${{ inputs.docker_image_name }}:${{ inputs.docker_tag_push }}
        # can have multiple tags is sepparated by a comma
    # - name: Kustomize
    #   if: ${{ inputs.use_kustomize }}
    #   uses: imranismail/setup-kustomize@v1
    #   with:
    #     kustomize-version: v3.6.1
    # - name: Update k8s images
    #   if: ${{ inputs.use_kustomize }}
    #   continue-on-error: true
    #   shell: bash
    #   run: |
    #     cd ${{ inputs.k8s_path_parent }}
    #     git pull
    #     cd main
    #     kustomize edit set image ${{ inputs.kustomize_image_name }}=${{ inputs.docker_registry }}/${{ inputs.image_name }}:${{ inputs.version_tag_kustomize_image }}
    #     cd ../bulk-indexer
    #     kustomize edit set image ${{ inputs.kustomize_image_name }}=${{ inputs.docker_registry }}/${{ inputs.image_name }}:${{ inputs.version_tag_kustomize_image }}
    #     cd ../maintenance
    #     kustomize edit set image ${{ inputs.kustomize_image_name }}=${{ inputs.docker_registry }}/${{ inputs.image_name }}:${{ inputs.version_tag_kustomize_image }}
    #     cd ../queue-processors
    #     kustomize edit set image ${{ inputs.kustomize_image_name }}=${{ inputs.docker_registry }}/${{ inputs.image_name }}:${{ inputs.version_tag_kustomize_image }}
    #     cd ../pub-key-transmitter
    #     kustomize edit set image ${{ inputs.kustomize_image_name }}=${{ inputs.docker_registry }}/${{ inputs.image_name }}:${{ inputs.version_tag_kustomize_image }}
    # - name: Update the trigger for ArgoCD
    #   if: ${{ inputs.use_kustomize }}
    #   continue-on-error: true
    #   shell: bash
    #   run: |
    #     echo "${{ github.ref }} -> ${{ inputs.version_tag_full }} -> ${{ github.sha }}" > .argocd-trigger-${{ inputs.version_tag_short }}
    # - name: Commit k8s
    #   if: ${{ inputs.use_kustomize }}
    #   continue-on-error: true
    #   shell: bash
    #   run: |
    #     git add .
    #     git config --local user.email "actions@github.com"
    #     git config --local user.name "CD Action"
    #     git commit -am "update kustomize image tags"
    # - name: Push changes
    #   if: ${{ inputs.use_kustomize }}
    #   continue-on-error: true
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ inputs.github_token }}
    #     branch: ${{ github.ref }}
