name: Kustomize
description: |
  Edits the kustomize files to update the image tags.
inputs:
  k8s_path:
    description: The path to the k8s directory
    required: true
  kustomize_repl_image_name:
    description: The name of the kustomize image
    required: true
    default: x-service-image
  docker_registry:
    description: The docker registry
    required: true
  docker_image_name:
    description: The docker image name
    required: true
  docker_tag:
    description: The docker tag
    required: true
  commit_message:
    description: The commit message
    required: true
    default: update kustomize image tags
  github_token:
    description: The github token secret
    required: true
  github_ref:
    description: The github ref
    required: true
runs:
  using: composite
  steps:
    - name: Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: v3.6.1
    - name: Update k8s images
      continue-on-error: true
      shell: bash
      run: |
        pushd ${{ inputs.k8s_path }}
        kustomize edit set image ${{ inputs.kustomize_repl_image_name }}=${{ inputs.docker_registry }}/${{ inputs.docker_image_name }}:${{ inputs.docker_tag }}
        popd
    - name: Commit k8s
      continue-on-error: true
      shell: bash
      run: |
        git add .
        git config --local user.email "actions@github.com"
        git config --local user.name "CD Action"
        git commit -am "${{ inputs.commit_message }}"
    - name: Push changes
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ inputs.github_ref }}
