name: CI

env:
  GOPRIVATE: go.pedidopago.com.br,github.com/pedidopago/*
  GOPROXY: direct

on:
  workflow_call:
    inputs:
      run_tests:
        description: "Run tests"
        required: false
        type: boolean
      run_coverage:
        description: "Run test coverage check"
        required: false
        type: boolean
      run_static_analysis:
        description: "Run static analysis check"
        required: false
        type: boolean
    secrets:
      DISCORD_WEBHOOK:
        required: false
        description: "Discord webhook URL"
      PPGITHUB_USER:
        required: true
        description: "GitHub username"
      PPGITHUB_TOKEN:
        required: true
        description: "GitHub token"
jobs:
  build:
    name: Build Go binary (linux x64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: WillAbides/setup-go-faster@v1.5.0
        with:
          go-version: 1.16.x
      - name: Retrieve Git Tokens
        env:
          USER: ${{ secrets.PPGITHUB_USER }}
          TOKEN: ${{ secrets.PPGITHUB_TOKEN }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com/pedidopago".insteadOf "git+ssh://git@github.com/pedidopago" --replace-all
          git config --global url."https://${USER}:${TOKEN}@github.com/pedidopago".insteadOf "https://github.com/pedidopago" --add
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: rm -rf vendor
      - name: Build CI binary via Mage
        env:
          BUILD_ENV: ci
          GOPRIVATE: go.pedidopago.com.br,github.com/pedidopago/*
          GOPROXY: direct
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: cibuild
  test:
    name: Test Go Code
    runs-on: ubuntu-latest
    needs: build
    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: "123456789"
          MYSQL_DATABASE: ms_temp
        ports:
          - 33306:3306
    env:
      DHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Retrieve Git Tokens
        env:
          USER: ${{ secrets.PPGITHUB_USER }}
          TOKEN: ${{ secrets.PPGITHUB_TOKEN }}
        run: |
          git config --global url."https://${USER}:${TOKEN}@github.com/pedidopago".insteadOf "git+ssh://git@github.com/pedidopago" --replace-all
          git config --global url."https://${USER}:${TOKEN}@github.com/pedidopago".insteadOf "https://github.com/pedidopago" --add
      - name: Install Go
        uses: WillAbides/setup-go-faster@v1.5.0
        with:
          go-version: 1.16.x
      - name: Test Go Code
        if: ${{ inputs.run_tests }}
        uses: magefile/mage-action@v1
        env:
          TEST_DBCS: "root:123456789@tcp(localhost:33306)/ms_temp?parseTime=true&collation=utf8mb4_general_ci&charset=utf8mb4,utf8&multiStatements=true"
        with:
          version: latest
          args: runalltests
      - name: Check test coverage
        if: ${{ inputs.run_coverage }}
        uses: magefile/mage-action@v1
        env:
          TEST_DBCS: "root:123456789@tcp(localhost:33306)/ms_temp?parseTime=true&collation=utf8mb4_general_ci&charset=utf8mb4,utf8&multiStatements=true"
          # MIN_TEST_COVERAGE: 9.99 # remove comment to override test coverage
        with:
          version: latest
          args: runtestcoverage
      - name: Notify Discord (tests)
        if: ${{ env.DHOOK != '' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The tests of {{ EVENT_PAYLOAD.repository.full_name }} have passed!"
      - name: Run static analysis
        if: ${{ inputs.run_static_analysis }}
        run: |
          go vet ./...
          $(go env GOPATH)/bin/staticcheck -go 1.16 ./...
      - name: Notify Discord (static analysis)
        if: ${{ env.DHOOK != '' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The tests of {{ EVENT_PAYLOAD.repository.full_name }} have passed!"
